version: "3.9"

services:
  db:
    image: postgres:16
    container_name: usermgmt_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: usermgmt_api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
